In [0]:
def comprobarcolum(matrix):
  verC=True
  verF=True
  tempc=0
  tempf=0
  for x in range(0,9):
    for y in range(0,9):
      tempc=matrix[x][y]
      # tempf=matrix[y][x]
      for i in range(0,9):
        for j in range(0,9):
          if(x!=i and y!=j and matrix[i][j]!=0):
            if(tempc==matrix[i][j]):
              print(tempc,' ',matrix[i][j], ' ',i,j, ' ',x,y)
              verC=False
              break;
            # if(tempf==matrix[j][i]):
            #   verF=False
  if(verC==False):
    print("Se repite un numero en la columna")
  if(verF==False):
    print("Se repite un numero en la fila")
  ver = verC and verF
  return ver

def comprobarcuad(matrix):
  vercuad=True
  tempcuad=[0,0,0,0,0,0,0,0,0]

  for x in range(0,9):
    for y in range(0,9):
      if(x<=2 and y <=2):
        tempcuad[0]=matrix[x][y]

      if((x>2 and x<=5) and y <=2):
        tempcuad[1]=matrix[x][y]

      if((x>5 and x<=8) and y <=2):
        tempcuad[2]=matrix[x][y]
##Segunda fila
      if(x<=2 and (y >2 and y<=5)):
        tempcuad[3]=matrix[x][y]

      if((x>2 and x<=5) and (y >2 and y<=5)):
        tempcuad[4]=matrix[x][y]

      if((x>5 and x<=8) and (y >2 and y<=5)):
        tempcuad[5]=matrix[x][y]
##ULtima fila
      if(x<=2 and (y >5 and y<=8)):
        tempcuad[6]=matrix[x][y]

      if((x>2 and x<=5) and (y >5 and y<=8)):
        tempcuad[7]=matrix[x][y]

      if((x>5 and x<=8) and (y >5 and y<=8)):
        tempcuad[8]=matrix[x][y]  
      
        for i in range(0,9):
          for j in range(0,9):
            if(x!=i and y!=j and matrix[i][j]!=0 ):    
                if(x<=2 and y <=2):
                  if(tempcuad[0]==matrix[i][j]):
                    vercuad=False

                if((x>2 and x<=5) and y <=2):
                  if(tempcuad[1]==matrix[i][j]):
                    vercuad=False

                if((x>5 and x<=8) and y <=2):
                  if(tempcuad[2]==matrix[i][j]):
                    vercuad=False
          ##Segunda fila
                if(x<=2 and (y >2 and y<=5)):
                  if(tempcuad[3]==matrix[i][j]):
                    vercuad=False

                if((x>2 and x<=5) and (y >2 and y<=5)):
                  if(tempcuad[4]==matrix[i][j]):
                    vercuad=False

                if((x>5 and x<=8) and (y >2 and y<=5)):
                  if(tempcuad[5]==matrix[i][j]):
                    vercuad=False
          ##ULtima fila
                if(x<=2 and (y >5 and y<=8)):
                  if(tempcuad[6]==matrix[i][j]):
                    vercuad=False

                if((x>2 and x<=5) and (y >5 and y<=8)):
                  if(tempcuad[7]==matrix[i][j]):
                    vercuad=False

                if((x>5 and x<=8) and (y >5 and y<=8)):
                  if(tempcuad[8]==matrix[i][j]):
                    vercuad=False
  return vercuad

def comprobar(matrix):
  ver=comprobarcolum(matrix)
  vercuad=comprobarcuad(matrix)
  verfinal = ver and vercuad
  if(verfinal==False):
    print("Hay un error, no tiene solución")
  return verfinal


# función que verifica si el sudoku está completo
def estaListo(tablero):
    for x in range(9):
        for y in range (9):
            if tablero[x][y] == 0:
                return False
    return True
    
# Función que encuentra las posibilidades haciendo las tres comprobaciones del sudoku
def numerosPosibles(tablero, i, j):
    
    arrayPosibilidades = {}
    
    for x in range(10):
        arrayPosibilidades[x] = 0
    
    # Posibilidades para horizontal y vertical
    for y in range (9):
        if not tablero[i][y] == 0: arrayPosibilidades[tablero[i][y]] = 1
        if not tablero[y][j] == 0: arrayPosibilidades[tablero[y][j]] = 1
            
    # Posibilidades para las subcuadriculas
    k = 0
    l = 0
    if i >= 0 and i <= 2: k = 0
    elif i >= 3 and i <= 5: k = 3
    else: k = 6
    if j >= 0 and j <= 2: l = 0
    elif j >= 3 and j <= 5: l = 3
    else: l = 6

    for x in range (k, k + 3):
        for y in range (l, l + 3):
            if not tablero[x][y] == 0:
                arrayPosibilidades[tablero[x][y]] = 1          
    
    for x in range (1, 10):
        if arrayPosibilidades[x] == 0:
            arrayPosibilidades[x] = x
        else:
            arrayPosibilidades[x] = 0
    
    return arrayPosibilidades

# función principal
def sudokuSolver(tablero, file):
    for i in range(9):
      for j in range(9):
        strcon=str(int(tablero[i,j])) + " "
        file.write(strcon)
      file.write("\n")
    file.write("\n")
    i = 0
    j = 0
    
    posibilidades = {}
    
    if estaListo(tablero):
        print(tablero)
        file.write("¡Listo! \n")
        return
    else:
        # Fija los espacios vacios
        for x in range (9):
            for y in range (9):
                if tablero[x][y] == 0:
                    i = x
                    j = y
                    break
            else:
                continue
            break
        
        # Función que me tira todas las posibilidades
        posibilidades = numerosPosibles(tablero, i, j)
        
        # Recorre el array de posibilidades y invoca la función que resuelve el sudoku
        for x in range (1, 10):
            if not posibilidades[x] == 0:
                tablero[i][j] = posibilidades[x]
                sudokuSolver(tablero, file)
        # La magia
        tablero[i][j] = 0
        file.write("Backtracking! \n")

import numpy as np
import os

sudoku = open('sudoku3.txt', 'r')

file = open("progreso.txt", "w")
file.write("Primera línea" + os.linesep)

tablero = np.zeros((9,9))
i = 0
for linea in sudoku.readlines():
  if (linea[0:1] != '*'): tablero[i,0] = linea[0:1]
  if (linea[1:2] != '*'): tablero[i,1] = linea[1:2]
  if (linea[2:3] != '*'): tablero[i,2] = linea[2:3]
  if (linea[3:4] != '*'): tablero[i,3] = linea[3:4]
  if (linea[4:5] != '*'): tablero[i,4] = linea[4:5]
  if (linea[5:6] != '*'): tablero[i,5] = linea[5:6]
  if (linea[6:7] != '*'): tablero[i,6] = linea[6:7]
  if (linea[7:8] != '*'): tablero[i,7] = linea[7:8]
  if (linea[8:9] != '*'): tablero[i,8] = linea[8:9]
  i = i + 1
print(tablero)
# comprobarval=comprobar(tablero)
# print('Comprobar: '+str(comprobarval))
# if(comprobarval==True):
sudokuSolver(tablero, file)
# else:
#   print("Sin solucion")
file.close()
sudoku.close() 

[[0. 0. 0. 5. 8. 0. 3. 1. 0.]
 [4. 0. 5. 0. 0. 2. 8. 0. 9.]
 [0. 0. 3. 0. 0. 9. 0. 0. 2.]
 [0. 0. 0. 7. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 6. 3. 5.]
 [0. 0. 0. 8. 0. 0. 2. 4. 7.]
 [0. 0. 4. 0. 9. 8. 0. 0. 0.]
 [0. 2. 0. 4. 3. 0. 0. 8. 0.]
 [0. 0. 9. 0. 0. 0. 4. 0. 6.]]
5.0   5.0   1 2   0 3
5.0   5.0   4 8   0 3
8.0   8.0   1 6   0 4
8.0   8.0   5 3   0 4
8.0   8.0   6 5   0 4
8.0   8.0   7 7   0 4
3.0   3.0   2 2   0 6
3.0   3.0   4 7   0 6
3.0   3.0   7 4   0 6
4.0   4.0   5 7   1 0
4.0   4.0   6 2   1 0
4.0   4.0   7 3   1 0
4.0   4.0   8 6   1 0
5.0   5.0   0 3   1 2
5.0   5.0   4 8   1 2
2.0   2.0   2 8   1 5
2.0   2.0   4 0   1 5
2.0   2.0   5 6   1 5
2.0   2.0   7 1   1 5
8.0   8.0   0 4   1 6
8.0   8.0   5 3   1 6
8.0   8.0   6 5   1 6
8.0   8.0   7 7   1 6
9.0   9.0   2 5   1 8
9.0   9.0   6 4   1 8
9.0   9.0   8 2   1 8
3.0   3.0   0 6   2 2
3.0   3.0   4 7   2 2
3.0   3.0   7 4   2 2
9.0   9.0   1 8   2 5
9.0   9.0   6 4   2 5
9.0   9.0   8 2   2 5
2.0   2.0   1 5   2 8
2.0