In [41]:
import numpy as np
sudoku = open('sudoku.txt', 'r')
m = np.zeros((9,9))
i = 0
for linea in sudoku.readlines():
  if (linea[0:1] != '*'): m[i,0] = linea[0:1]
  if (linea[1:2] != '*'): m[i,1] = linea[1:2]
  if (linea[2:3] != '*'): m[i,2] = linea[2:3]
  if (linea[3:4] != '*'): m[i,3] = linea[3:4]
  if (linea[4:5] != '*'): m[i,4] = linea[4:5]
  if (linea[5:6] != '*'): m[i,5] = linea[5:6]
  if (linea[6:7] != '*'): m[i,6] = linea[6:7]
  if (linea[7:8] != '*'): m[i,7] = linea[7:8]
  if (linea[8:9] != '*'): m[i,8] = linea[8:9]
  i = i + 1
print(m)
sudoku.close() 

[[0. 9. 0. 0. 8. 0. 3. 6. 0.]
 [0. 7. 6. 0. 0. 4. 0. 0. 0.]
 [2. 5. 8. 3. 6. 0. 0. 0. 0.]
 [6. 0. 0. 0. 3. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 9. 0. 1. 8.]
 [8. 0. 0. 6. 0. 0. 0. 0. 0.]
 [7. 0. 2. 0. 1. 0. 0. 0. 9.]
 [4. 8. 0. 0. 9. 0. 0. 0. 6.]
 [0. 0. 5. 7. 0. 2. 0. 0. 0.]]
